### ISSUE TITLE
Gateway Password

### ISSUE THREAD

**Issue by bluefoxlee** [snOOrz/homebridge-aqara#1]
How can user get Aqara Getway's password? 
is it the same as Xiaomi account password? (not likely)

**Comment by snOOrz** [comment]
No.
It's a simple password stored in the local gateway.

The firmware is not officially released yet, you may need to wait 2 more weeks.

**Comment by bluefoxlee** [comment]
> It's a simple password stored in the local gateway.
> The firmware is not officially released yet, you may need to wait 2 more weeks..

Got it, and Thanks snOOrz.
Can't wait to how it goes on Aqara smart home set.
Wonder does the new firmware going to work with MiRouter plug as well?

Anyway, Thanks for the plug and hard work.

**Comment by javefang** [comment]
Hi there, it's an awesome idea to connect homekit to aqara! Would you mind explaining how should I retrieve the password for the gateway? (simple password stored in the local gateway)

**Comment by javefang** [comment]
Ah I think I got it. Is the password hard coded into the firmware (which is why we are waiting for it?)

**Comment by snOOrz** [comment]
You need a new firmware to support local network communication, not only the password.

发自我的 iPad

**Comment by bluefoxlee** [comment]
sorry to bring out another question (or should I raise another topic?)

I see there are Aqara zibgee switch (one and two button) have been added, are we going to see Zigbee plug added later as well?

**Comment by javefang** [comment]
@snOOrz once the new firmware is released, will there be an interface showing what the password is? (through the app or something?)

**Comment by bluefoxlee** [comment]
@snOOrz Thanks. I see plug has been added to the plug. cool!
can't wait to see new firmware released.

**Comment by supernial** [comment]
Can't find any information on this . Are you talking about the Xiaomi Gateway? And why is it important to get the Firmware?

**Comment by bluefoxlee** [comment]
@supernial Xaiomi Gateway, so call Aqara gateway here. This plugin is unable to use until new firmware released.

**Comment by supernial** [comment]
Kind thought so. Just wasn't sure why people sometimes refer to Xiaomi's product by the name of the subcompany Aqara. I'm currently on 1.3.0_124 . I presume that is still not open for plugin. And i deduce that xiaomi is slowly opening the communication api to be able to interact with other IoT vendors?

**Comment by snOOrz** [comment]
You can find all you need here, http://bbs.xiaomi.cn/t-13198850

**Comment by bluefoxlee** [comment]
In case any one need it, I did a quick English translation below:
https://goo.gl/gEVIrn

@snOOrz hope you don't mind with English translation.

**Comment by supernial** [comment]
Everyone thank you for such support and detailed explanation. That helped a lot. And now is clear to me.  I still have a problem on my gateway. When i click "OK" on local protocol selection screen nothing happens. I can only click cancel and that closes the screen. When i get back, local protocol is disabled.

**Comment by supernial** [comment]
I presume that my version is still old and i simply can't turn on local protocol support yet

**Comment by bluefoxlee** [comment]
@supernial Ver.1 or Ver.2?(actually I believe it's v2&v3 for Xiaomi) Have you try to reboot the gateway? I got blind failed at beginning. Got issue fixed after reboot. going to make a test wit my v1 gateway at another building tmr.

**Comment by supernial** [comment]
Its a version 2.14 . Very strange thing that when i go to the screen to enable local protocol. It has a spinning (Loading) icon in the bottom of the screen and then in password field it says "method not supported" .  Then I click refresh and password gets generated and the message goes away and password is shown.

**Comment by supernial** [comment]
Here is what i mean
https://drive.google.com/folderview?id=0B92ha3FcOzJcRURfNjhPa2ZVMmM

**Comment by snOOrz** [comment]
@supernial You need firmware version 1.3.1_140.0141 to make it work.

**Comment by supernial** [comment]
I hink I get it now. I probably have an old hardware version of a gateway. And I need to buy a new one. Because I don't see any internet radio funcionality. I think that the new functionality only comes with DGNWG02LM this model and it can be upgraded to 1.3.1_140.0141

**Comment by snOOrz** [comment]
Yes, I agree. I don't have old version hardware but I guess it's too old to support this feature.

Date: Tue, 11 Oct 2016 11:53:08 -0700

**Comment by supernial** [comment]
Hi again. So some time has now passed and i got two new  02LM gateways now. Is the new firmware released already? I can't find it anywhere.

**Comment by 3ZVK** [comment]
I also have the method not found error when trying to validate the password on my new-gen gateway, any way to solve this ?

**Comment by adekka** [comment]
The same problem here. Android says 'no method found' and my iPhone says 'retrieve failed'. Someone any luck on this?

**Comment by maclandrol** [comment]
Same problem,  'no method found' and the firmware is stuck to 1.2.6

**Comment by rpetteruti** [comment]
I get 'no method found' no way to enable the developer mode. I have the model: DGNWG02LM.
There is any way to force the firmware update?
Thank you

**Comment by Raidok** [comment]
I just got my gateway from the mail and trying to set up homebridge but I'm also getting 'retrieve failed' on iPhone. Hardware version is also DGNWG02LM. After multiple updates firmware ended up being 1.4.1_142.0141

**Comment by yecine06** [comment]
I am having the same issue "retrieve failed" even after killing the app the result is the same, I tried to reboot the gateway same thing 

I don't have an android phone to try anyone had successfully done it lately with the latest firmware?

**Comment by supernial** [comment]
I have done it successfully.  But had to change my hardware to be atleast 02LM . That had update just recently and I was able to see the state in my iPad

**Comment by Raidok** [comment]
I too cannot get past the "retrieve failed" any more but when I did, the data was not broadcasted to the network so I have not gotten it to work.

I assume that changing the hardware means buying a new gateway. Where ban I see what hardware version do I have?

**Comment by supernial** [comment]
The version is on the back of the gateway . On a sticker. If you have L01 youre out of luck. This one is not going to support network communications

**Comment by Raidok** [comment]
Oh I remember reading about that too a while ago. I checked and mine is also ending with 02LM but cannot get to work with iOS app. I guess I'll have to try with Android then.

**Comment by supernial** [comment]
Exactly. I had L01. But it would never update to 1.4.1_142.0141 . So I got L02 from gearbest.  Updated my Home App to version 2.19. New version of the app upgraded my L02 gateways to 1.4.1_142.0141 . That solved everything.  Additionally I got Internet radios which come with L02 version.  Never use them. And don't know how to add mine.

**Comment by adekka** [comment]
It only worked for me on the first try. So close the app and then try it again. Maybe it helps..

**Comment by supernial** [comment]
Forgot to mention. My app is running on Android.

**Comment by jmvermeulen** [comment]
I had the same 'retrieve failed' problem with the iOS version and I don't have any Android device at home.

So I used a (free) Android emulator droid4x from:
https://droid4x.en.uptodown.com/windows/download

And downloaded the APK http://www.apkmirror.com/apk/xiaomi-inc/mihome/mihome-3-9-20-release/mihome-3-9-20-android-apk-download/download/

It worked without any issues!

**Comment by Raidok** [comment]
I went through the hassle to run the Android app in an emulator to find out that I actually had previously managed to enable the local network broadcasts. So the issue had to be somewhere else..
Previously I had tired to run it on a Mac but I followed the guide to [set up homebridge on a Raspberry Pi](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi) and got it to work! I used LTS version of nodeJS which currently is v6.9.4 because this extension uses API that exists since v6.0.0
