### ISSUE TITLE
Xiaomi Gateway v1

### ISSUE THREAD

**Issue by Rockman18** [snOOrz/homebridge-aqara#11]
Hello,

Can we hope a firmware update of the 1st version of the gateway to add this useful (quite mandatory) feature ?
Desperately blocked on version 1.3.0_124.0140 for over a month.

Thx

**Comment by snOOrz** [comment]
A I know, v1 gateway hardware has not enough space for this feature.

**Comment by Rockman18** [comment]
Sad news, thank you
