### ISSUE TITLE
Still on firmware 1.2.6

### ISSUE THREAD

**Issue by sballoz** [snOOrz/homebridge-aqara#13]
Hello

I have bought a new v2 hub (I was on v1) purely because I wanted the HomeKit integration. Received it yesterday, installed it. Can't upgrade to 1.3.1. 
Mihome app (last version, tried on android and iOS) says that I have the most updated firmare (1.2.6).
Furthermore I can't activate developer mode on the app, is this due to the fact that the firmware is not updated?
Please help me out. I wrote to Xiaomi support with no response.

**Comment by stofakiller** [comment]
Hi,

Exactly the same here, do we need a xiaomi developer account?

Regards
Jan

**Comment by sballoz** [comment]
I don't know, I spent all night trying to find a solution with no luck

**Comment by SublimePotato** [comment]
As far as I know Xiaomi rolled back the latest update (1.3.1) since it had problems with certain Apple routers.  

Seems like waiting is the best option for now.

**Comment by sballoz** [comment]
Hi

Thanks for your Message
Unfortunately From Android if I tap repeatedly on 2.1.4 I get a chinese message but no New options. It is weird because with my previous Android phone (sold last week) and the v1 hub I was able to get the 2 options

**Comment by stofakiller** [comment]
Hi,

It came with an update of the app, im on ios, and my v1 its gone, but i can with my v3 (latest with radio)

**Comment by mgarmash** [comment]
Same problem here. Looks like they really rolled back last update.
This is what i found http://bbs.xiaomi.cn/t-13196534

**Comment by sballoz** [comment]
It works now

**Comment by SublimePotato** [comment]
Still no update aviable for me.  

@sballoz so you are on 1.3.1 now?

**Comment by sballoz** [comment]
1.4.1 and I also could activate the developer mode from IOS

**Comment by sballoz** [comment]
In the next few days I will try the home bridge plugin and let you know if it works

**Comment by ChesterZhou** [comment]
Yes, one month passed. It is still 1.2.6... I will try Yeelight first. It works from another github.

**Comment by stofakiller** [comment]
Xiaomi seems to let people update firmware in "waves", i have several Xiaomi cameras, and i cant update firmware on all at once, probaly not to overload the servers etc

**Comment by sballoz** [comment]
I can confirm that I have 1.4.1 installed and can see things on my iPhone. I have some issues but I will post a new thread more relevant

**Comment by snOOrz** [comment]
@babymoney666 please help

**Comment by bluefoxlee** [comment]
@snOOrz will it be better if Xiaomi can host a beta group so people can apply for it if they are willing to test and have no problem with potential bugs. ( I remember Xiaomi do have this kind of system.)

**Comment by 3ZVK** [comment]
@babymoney666 please help me too i'm stuck 1.2.6

**Comment by bluefoxlee** [comment]
@snOOrz how are we going to contact with @babymoney666 for firmware upgrade since ther is no email and no PM with Github.

**Comment by acrueda** [comment]
@babymoney666 Hello, could you help me to install version 1.4.1_141.0141 or higher on my V2 gateway. Thank you

**Comment by bluefoxlee** [comment]
The new firmware just released today.

**Comment by mooyoul** [comment]
Yeah I just updated my firmware to v1.4.1 :)

**Comment by 3ZVK** [comment]
same here FW 1.4.1 thanks all !

**Comment by mgarmash** [comment]
Updated successfully to 1.4.1, but can't enable Local Area Network Protocol. After clicking right button (looks like OK/Accept in translation) it shows message "bind failed" 
![img_1703](https://cloud.githubusercontent.com/assets/453401/20675979/6495e3e4-b5b8-11e6-9519-7111e1cd1e0c.JPG) is it ok?

**Comment by mgarmash** [comment]
It is strange, but after some tries it succeed.
