### ISSUE TITLE
No password for 158d00011*****, please edit ~/.homebridge/config.json

### ISSUE THREAD

**Issue by ChesterZhou** [snOOrz/homebridge-aqara#17]
Everything was configured perfectly and all accessories can be found in HomeKit. But if I click the light button. The error message show up no password for the light and require edit config file. I double checked the password for the gateway and no error. Do we need add the light's mac into the config file but I cannot find the password.

**Comment by snOOrz** [comment]
I guess something wrong in your config.json. Can you paste it to this thread?

**Comment by dx4wraith** [comment]
I have the same problems.The Aquara button on the wall need password?

**Comment by ChesterZhou** [comment]
Thanks for your reply. Here is the config.json file. For the password, I tried both up and lower case but the same error message.

`{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51936,
                "pin": "987-65-556"
        },
        "platforms": [
        {
                "platform": "AqaraPlatform",
                "sid": ["fob429cbe7df"],
                "password": ["87D8DB0C779748B1"]
        }]
}`

**Comment by dx4wraith** [comment]
我尝试了好久了，实在是找不到关于aquara墙壁开关的密码配置方法

**Comment by ChesterZhou** [comment]
不仅仅是墙壁开关，我这跟网关连着的两个插座也能显示出来，但是点击后都提示No password

**Comment by Sagwed** [comment]
@ChesterZhou  你的 sid 有问题 应该是 f0b429cbe7df , MAC 地址是16进制，不会出现 abcdef 之外的其他字母，所以第二个应该是 0。
Sid "fob429cbe7df" in your config.js has wrong character  'o', it must be zero '0'.

**Comment by dx4wraith** [comment]
很多用aquara开关的都遇到这问题了，只不过没人在github上反应

**Comment by ChesterZhou** [comment]
Thanks for your reply. I will try this later.

**Comment by zzc1308** [comment]
这个问题解决了，要把config.json里的mac地址换成小写。。。
solved,please change the mac address into lowcase in config.json,good luck!
