### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by austin-web** [snOOrz/homebridge-aqara#28]
感谢你的homebridge-aqara  什么时候能够支持， 小米空气净化器。 米家台灯。 其他小米关联设备啊。

**Comment by bluefoxlee** [comment]
乐见小米可以增加其他支持、不过Zigebee与Wifi模组应该不同才是

**Comment by snOOrz** [comment]
This plugin only supports Zigbee devices. To support other WiFi devices, you need other plugins, e.g. homebridge-yeelight
