### ISSUE TITLE
Any news on the new firmware?

### ISSUE THREAD

**Issue by javefang** [snOOrz/homebridge-aqara#3]
Really looking forward to it :)

**Comment by bluefoxlee** [comment]
I believe China is in national holiday this week, so I supply we probably need to wait until next week.

**Comment by javefang** [comment]
Just got firmware update today, now at 1.3.1_140.0141, is that going to work with homebridge now?

**Comment by Rockman18** [comment]
Still waiting for the update. Which version of the gateway do you have? 
- 1st version : no radio, no custom bell.
- 2nd version : radio & custom bell.

Check in the MiHome app if a new menu appears with a password to access the gateway on local network.

**Comment by javefang** [comment]
I have 2nd version. Just had a look into the MiHome App but I can't seem to find the option. Do you know where in the app should I look for the option?

**Comment by Rockman18** [comment]
Absolutely not... Perhaps in "Network Info" in the Gateway settings.
I have the first version of the gateway and still no update there.

**Comment by snOOrz** [comment]
1.3.1_140.0141 is the latest, it works now but you still need to wait for iOS version of Mijia app to be updated. Android version of Mijia app is ready for this feature, I'll post the how-to link in README.

**Comment by javefang** [comment]
I may give it a go with my Android phone later :) Thank you for the good work!

**Comment by bluefoxlee** [comment]
Still waiting. Wonder if it's generated from SID? if you long press on "feedback", you can get gateway SID number (or can see it directly from developer version of Mijia apk.

**Comment by snOOrz** [comment]
You can find all you need here, http://bbs.xiaomi.cn/t-13198850

**Comment by bluefoxlee** [comment]
I have no problem with Chinese and get it working now. Thanks @snOOrz 

In case any one need it, I did a quick English translation below:
https://goo.gl/gEVIrn

**Comment by bastshoes** [comment]
Is there any option to force FW update? I've got gateway ver. 2 with FW 1.2.6_138.0141. MI app ver. is 3.9.10. When I checking for fw update it says that I've got latest fw.

**Comment by bluefoxlee** [comment]
I heard they pull out 1.3.1 since there is a connection issue with some Wireless routers. (Apple Airport?).

**Comment by bastshoes** [comment]
Thanks for update. Yesterday I've got my device. Wanted to turn on LAN communication but device return "Method not found". Will wait for new FW.

**Comment by bluefoxlee** [comment]
Wonder is there any chance Xiaomi will update MC200 version (ver.1) too.

**Comment by mooyoul** [comment]
I couldn't receive 1.3.1 update too. app says "1.2.6 is latest version". is any news exists?

**Comment by javefang** [comment]
Thank you @snOOrz for the great work! I got it to work with homebridge now! I'll close this issue as the discussion is no longer specific to the firmware of gateway ver. 2 anymore.

**Comment by supernial** [comment]
I got my update 2 days ago
