### ISSUE TITLE
Xiaomi Aqara Smart Light support?

### ISSUE THREAD

**Issue by jul9000** [snOOrz/homebridge-aqara#30]
Hey, thanks for your great work snOOrz! My sensors and LED bulbs are working flawlessly and I'm thinking about adding more devices.

Are you going to implement the Xiaomi Aqara Smart Light switches? I'm considering buying some of these to control my Xiaomi LED bulbs. 

I'm talking about this these: http://xiaomi-mi.com/smart-home/xiaomi-aqara-smart-light-control-set/
http://files.xiaomi-mi.com/files/aqara/aqara-EN.pdf

**Comment by snOOrz** [comment]
The light switches support are already done.

On 2017年1月14日 +0800 06:29, jul9000 <notifications@github.com>, wrote:

Hey, thanks for your great work snOOrz! My sensors and LED bulbs are working flawlessly and I'm thinking about adding more devices.

Are you going to implement the Xiaomi Aqara Smart Light switches? I'm considering buying some of these to control my Xiaomi LED bulbs.

I'm talking about this these: http://xiaomi-mi.com/smart-home/xiaomi-aqara-smart-light-control-set/
http://files.xiaomi-mi.com/files/aqara/aqara-EN.pdf

**Comment by jul9000** [comment]
Great news, thanks!
