### ISSUE TITLE
Magnet returns "open" when gateway is blocked from the internet.

### ISSUE THREAD

**Issue by SublimePotato** [snOOrz/homebridge-aqara#32]
Out of privacy reasons I blocked the gateway from accessing the internet via my router, now the gateway behaves odd in 3 ways:

1. Door magnet sensor returns "open" after it's been closed for an hour and stays in that state. Opening and  closing the door corrects the status but after another hour the sensor returns "open" again.
2. When turning on the gateway light, by pressing the button, the light turns on as it should but after a few minutes the light is turned off and replaced by blue blinking.
3. Occasional blue blinking (surely to tell that it has no internet access) 

I monitored these issues for about 3 months now and tried restarting, reinstalling, resetting and updating to solve the problem - sadly without success.

**Has someone else encountered these and has a fix for them?**

**Comment by snOOrz** [comment]
Does it work if you unblock the gateway from internet?

On 2017年1月18日 +0800 02:43, Mx. Prssbrgr <notifications@github.com>, wrote:

Out of privacy reasons I blocked the gateway from accessing the internet via my router, now the gateway behaves odd in 3 ways:

  1.  Door magnet sensor returns "open" after it's been closed for an hour and stays in that state. Opening and closing the door corrects the status but after another hour the sensor returns "open" again.
  2.  When turning on the gateway light by pressing the button the light turns on as it should but after a few minutes the light is turned off and replaced by blue blinking.
  3.  Occasional blue blinking (surely to tell that it has no internet access)

I monitored these issues for about 3 months now and tried restarting, reinstalling, resetting and updating to solve the problem - sadly without success.

Has someone else encountered these and has a fix for them?

**Comment by Rockman18** [comment]
Mine has the same behavior since last update. But mine accesses Internet without problem, I don't block internet access.
My magnets report open on "heartbeat" after à while even if it's closed

**Comment by SublimePotato** [comment]
@snOOrz 
It works for me when the gateway has access to the internet. But after reading @Rockman18's comment, it's maybe also an important fact that I had the Mi Home app installed with the same event (magnet opens) configured in there. 

The app never returned the false open and when my gateway was connected to the internet homebridge & homeassistant were working correctly too. 

I will try again without the app to check whether the it's doing magic to make it work or not.

@Rockman18 
Are you using the Mi Home app?

**Comment by Rockman18** [comment]
@SublimePotato 
I use Mi Home all the time. My scenes are configured on Mi Home, the magnets are well reported as closed. For the moment, I use the local API for logging purpose only

**Comment by SublimePotato** [comment]
It's not the Mi Home app.
The moment my Gateway has access to the internet, all described problems are gone. It does not matter if the app is active or not. It may be the configuration I did tho, since it is saved on chinese servers which probably still monitor everything even if there is no app signed in.
Too bad it's no option for me to have a potential datacollector in my intranet, so I will live with the sensor not working correctly for now. 

If anyone has a fix for this you are welcome to let me know.
