### ISSUE TITLE
Can't see any accessory.

### ISSUE THREAD

**Issue by dozer47528** [snOOrz/homebridge-aqara#42]
I setup the `homebridge-aqara` successfully without any error.

And I can add the homebridge in Homekit.

But I can't see any accessory in my GateWay.

![img_0897](https://cloud.githubusercontent.com/assets/1676951/23585412/c0213022-01b9-11e7-863c-b5ccb8975373.PNG)

![img_0898](https://cloud.githubusercontent.com/assets/1676951/23585419/06414858-01ba-11e7-9fda-86319bda79ce.PNG)

**Comment by magichew** [comment]
I have the same issue here. I have full use of door sensor, motion sensor and button via the Mi app but nothing shows up in Home app other than Homebridge.

I've configured homebridge successfully before with the Mi Light plugin and have that working fine but stripped everything out of my json config file to try to get this working.

I see this is closed so I'd love to be pointed in the direction of the solution.

**Comment by astrojetson8** [comment]
check your config, and make sure you've correct mac address in all lower case.

**Comment by magichew** [comment]
Thanks for replying. I looked again at the password and it didn't match what I had previously entered. Seems like the password must change?

**Comment by xuqisheng** [comment]
password need lower case ??? -.-!!!
