### ISSUE TITLE
温湿度传感器温度部分未响应

### ISSUE THREAD

**Issue by junyilou** [snOOrz/homebridge-aqara#49]
Home App 刷新状态后 温湿度传感温度部分未响应 湿度正常 米家 App 中两者均可以正确显示 重启 Homebridge 问题解决 刷新后再次失效

**Comment by qdwhltop** [comment]
温度湿度确实有相应延迟的现象，过段时间会就可以了。

**Comment by jayqizone** [comment]
是因为米家温湿度传感器是一体的，而实际上对应到homekit是两个sensor

插件目前在处理时，认为每次总能同时获取到temperature、humidity数据，然后同时更新这两个sensor


实际上抓包可以看出：

1、每300秒插件发出的“whois”指令时，针对温湿度传感器，gateway代理确实会返回同时含有temperature、humidity的报文，这种情况下，两个sensor都能正确刷新

2、除了这种定期的轮询，sensor也会主动report，比如门窗传感器会在开闭的时候主动更新状态。而温湿度传感器，有时候会主动report仅包含humidity信息的报文，于是插件在计算temperature时出现了NaN数值错误，表象就是homekit中显示异常

特别的，我并没有观察到过仅上传temperature信息的案例，因此，也没有遇到过humidity传感器异常的情况


因此，时常会观察到温度失灵，而过一会又好了的现象（每300秒的被动更新会刷新正确的数据）

可以认为是gateway或sensor的缺陷，不过插件可以轻松解决，已提交PR，可以参考

**Comment by snOOrz** [comment]
@jayqizone thanks, your PR has been merged.
@junyilou could you please update homebridge-aqara and test again?
