### ISSUE TITLE
aqara sensors at random revert back to default name and default room

### ISSUE THREAD

**Issue by astrojetson8** [snOOrz/homebridge-aqara#50]
In Home, some sensors at random revert back to default name and default room. And this has happened to me more than dozen or so times.
This has never happen to me with either Yeelight or Wemo.

Anyone else experienced this issue? And do you have a suggested fix for me?

I'm running homebridge on mac, and firmware on my gateway is 1.4.1_143.0141

**Comment by richen** [comment]
count++

**Comment by astrojetson8** [comment]
i suspect it's to do with zigbee plugs cause i left them in their default name and room, and so far it hasn't caused any aqara accessory to revert back to default in last 2 days. usually the above issue happens few times a day for me.

**Comment by astrojetson8** [comment]
also, i think it could be offline switch thats cause the root issue here.

**Comment by astrojetson8** [comment]
iOS 10.3 seems to not have this issue.

**Comment by fxdpz** [comment]
i am using pi and ios 10.3.1. motion sensor and light switch will revert to default at night, not sure why.

**Comment by theo-69** [comment]
having the same problem so it should not be closed
