### ISSUE TITLE
Homebidge failed after sensors rename

### ISSUE THREAD

**Issue by oleg77s** [snOOrz/homebridge-aqara#73]
config:
{
            "platform": "AqaraPlatform",
            "sid": ["xxx"],
            "password": ["xxx"],
        "sensor_names":
         {
        "37a1":"Toilet" 
                        }
Log:
May 14 16:56:35 raspberrypi-0W homebridge[29648]: [5/14/2017, 4:56:35 PM] Resetting saved name 37a1 -> Toilet
May 14 16:56:35 raspberrypi-0W homebridge[29648]: /usr/local/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:52
May 14 16:56:35 raspberrypi-0W homebridge[29648]: var characteristic = service.getCharacteristic(Characteristic.Name);
May 14 16:56:35 raspberrypi-0W homebridge[29648]: ^
May 14 16:56:35 raspberrypi-0W homebridge[29648]: ReferenceError: service is not defined
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at AqaraAccessoryFactory.configureAccessory (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:52:35)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at AqaraPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:190:16)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:342:24)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:83:8)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Module._compile (module.js:570:32)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Object.Module._extensions..js (module.js:579:10)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Module.load (module.js:487:32)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at tryModuleLoad (module.js:446:12)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Function.Module._load (module.js:438:3)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at Module.runMain (module.js:604:10)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at run (bootstrap_node.js:390:7)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at startup (bootstrap_node.js:150:9)
May 14 16:56:35 raspberrypi-0W homebridge[29648]: at bootstrap_node.js:505:3
May 14 16:56:35 raspberrypi-0W systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
May 14 16:56:35 raspberrypi-0W systemd[1]: Unit homebridge.service entered failed state.

**Comment by wlongxiang** [comment]
got the same problem after renaming

**Comment by seikan** [comment]
I'm having same issue. The "service" variable is not defined.

**Comment by jelvs** [comment]
it's probably better, just to rename it on Apple Home app instead of doing on the config,i did it, and it works just fine

**Comment by timh1004** [comment]
Try deleting ~/.homebridge/accessories/cachedAccessories

**Comment by phenomeus** [comment]
reseting …accessories/cachedAccessories did the trick
