### ISSUE TITLE
Gateway password not needed for getting sensor data?

### ISSUE THREAD

**Issue by javefang** [snOOrz/homebridge-aqara#8]
I'm working home-assistant integration (also mentioned [here](https://github.com/snOOrz/homebridge-aqara/issues/7))

One interesting finding, it looks like the password is not needed for reading sensor data? (only needed for controlling the lights, see [code](https://github.com/snOOrz/homebridge-aqara/blob/master/lib/AqaraPlatform.js#L412))

All sensor data are just multicasted to 224.0.0.50:4321 and I can write a simple script to read them without the gateway password.

This implies two things:
1. Any device on the same network can read the sensor data.
2. Anyone on the same network can spoof the gateway by sending fake sensor data.

Not a great deal for me but just posting here in case anyone is interested. 

@snOOrz, it seems signing/encrypting the multicasted sensor data is technically possible, is there a reason why this is not implemented?

**Comment by mooyoul** [comment]
I'm assuming that encryption key was related to encrypted packet payload (usally from UDP 54321, to Xiaomi Server, Packet has 16 bytes of header part, and body part is encrypted by using AES-128-CBC. I could't find AES passpharse/iv are came from). 

I think that encryption feature **can be** added on multicast method in future.

**Comment by bastshoes** [comment]
Have you upgraded gateway? 
I'm also interested in HA  integration but can't upgrade fw.

**Comment by fooxy** [comment]
I managed to create a custom component to communicate with temperature sensors. 
But when states updates, values are mixed-up (see history screenshot below).
Maybe it's due to async protocol or something else.
I'm novice to python.

## Badges
![screenshot](https://img42.com/StSV6+)

## History
![screenshot](https://img42.com/W4TYF+)

## a piece of code

```javascript
def setup_platform(hass, config, add_devices_callback, discovery_info=None):
    """Setup the sensor platform."""

    sensorItems = []

    devices = [
    {"name":"Living-romm","sid":"XXXXXX"},
    {"name":"Bedroom 1","sid":"XXXXXX"},
    {"name":"Bedroom 2","sid":"XXXXXX"}
    ]
    for device in devices:
        deviceCmd = '{"cmd":"read", "sid":"' + device['sid'] + '"}'
        htSensorData = HTSensorData(deviceCmd)
        sensorItems.append(HTSensor(htSensorData,device['name'], device['sid']))

    add_devices_callback(sensorItems)

class HTSensor(Entity):
    """Representation of a Sensor."""

BLABLA.....

  def update(self):
        """ Gets the latest data and updates the state. """
        self.deviceData.update()
        value = self.deviceData.value
        if value is not None:
            self._state = value

class HTSensorData(object):
    """ Class for handling the data retrieval. """

BLABLA.....

    def __init__(self, command):
        self.command = command
        self.value = None

    @Throttle(MIN_TIME_BETWEEN_UPDATES)
    def update(self):
        """ Gets the latest data with a shell command. """
        self.value = self.socketSendMsg(self.command)

BLABLA.....
```

**Comment by snOOrz** [comment]
Jave,
    You are right, thanks.
    Encrypting read only data is possible but will use lots of CPU cycles. It may turn the gateway much slower because the CPU is not very fast enough, so it's called MCU instead of CPU.


发自我的 iPad

**Comment by javefang** [comment]
Thanks @snOOrz, that makes sense. I'll close the issue
