### ISSUE TITLE
two button aqara switch not showing

### ISSUE THREAD

**Issue by theo-69** [snOOrz/homebridge-aqara#83]
I have a two button Wall switch (with batterie) and its not showing on homebridge or in the log.... My password is already uppercase!

**Comment by januslo** [comment]
#69

发自我的 iPhone

**Comment by theo-69** [comment]
not working

**Comment by theo-69** [comment]
oh password is uppercas

**Comment by theo-69** [comment]
now the show but as light bulb how do i change them to switch?

**Comment by theo-69** [comment]
now its gone again 👎
