### ISSUE TITLE
aqara会导致homebridge软件异常退出

### ISSUE THREAD

**Issue by zhang8083** [snOOrz/homebridge-aqara#9]
测试发现，在home里面快速开关动作，会导致homebridge软件异常退出。
发现的规律是这样的，切换到相同状态的时候，软件会异常退出，比如现在开关是开的状态，如果快速开关动作，在开还没有完全执行的条件下，又切换到开的状态，这样程序就会异常退出，试过在AqaraPlatform.js 里面函数LightswitchCommander.prototype.send里面 把this.lastValue==on 条件下的return屏蔽掉，重新测试，软件不会死掉，但是功能异常，设备无法控制，只能重启homebridge才能恢复。
这个bug还有个问题，就是会导致home里面场景执行可能会出现异常。比如我设置的场景里面把灯关闭，在执行场景前灯是关闭状态，那边我执行场景后，软件也会崩溃。
这个问题请问怎么解决呢？

**Comment by nichwang88** [comment]
快速开关，homebridge异常退出的问题我没有遇到，楼主可以尝试将homebridge加入自启动项目，异常退出也会自动重启进程的方式临时解决。
场景执行奔溃的问题，我倒是确实碰到了，我测试只有在灯泡全开的情况下才能执行晚安关灯操作，一旦有某几盏灯本来就是关闭状态的就会执行失败，然后重新加载homebridge。

**Comment by zhang8083** [comment]
@nichwang88 谢谢您的回复，所以现在的主要的问题就是，开关在某种状态下，如果你再让他进入同一个状态，就会导致homebridge崩溃的。我自己也写了一个脚本，定时监测homebridge进程，如果发现进程不在了，就重启homebridge。可以临时解决，homebridge崩溃的问题。 平时开关过程中只要不按太快出现同状态切换的情况，可以避免软件崩溃，但是场景就没办法控制了，比如离家模式，我要让所有的灯或者开关关闭，但是之前开关本来就是关闭状态，这种情况只能把设备都开启，然后再激活离家模式，才可能避免程序不崩溃了 ：（

**Comment by Sagwed** [comment]
难道你们没发现AqaraPlatform.js 399 行代码报错吗？
```
  // Dont' send duplicate command out.
  if (this.lastValue == on) {
    platform.log.debug("Value not changed, do nothing");
    return;
  }
```
这里的 platform.log.debug 这一行应该注释掉，或者将下面 var platform = this.platform; 提前

**Comment by zhang8083** [comment]
@Sagwed 谢谢兄弟，移到前面去可以了:)

**Comment by nichwang88** [comment]
楼上两位兄弟，我对编程不怎么了解，"var platform = this.platform"提前到哪里，能说仔细点吗？谢谢！

**Comment by Sagwed** [comment]
@nichwang88 直接注释掉399行 platform.log.debug("Value not changed, do nothing"); 好了
反正调试信息也没用。如果要保留这行的话
```
LightSwitchCommander.prototype.send = function(on) {
  // Dont' send duplicate command out.
  if (this.lastValue == on) {
    platform.log.debug("Value not changed, do nothing");
    return;
  }

  var platform = this.platform;
  var password = platform.passwords[this.deviceSid];
```
var platform = this.platform; 提到 if 前面改成
```
LightSwitchCommander.prototype.send = function(on) {
  var platform = this.platform;
  // Dont' send duplicate command out.
  if (this.lastValue == on) {
    platform.log.debug("Value not changed, do nothing");
    return;
  }

  var password = platform.passwords[this.deviceSid];
```

**Comment by nichwang88** [comment]
@Sagwed 多谢，搞定了，果然是高手。
