### ISSUE TITLE
One of my temperature sensors isn't supported

### ISSUE THREAD

**Issue by iCarl** [snOOrz/homebridge-aqara#90]
One of my temperature sensors says it isn't supported.
The humidity sensor works (same device).
When I try editing the accessory in the Home app, it just says its blocked.
Has anyone experienced the same issue, and if so, how do i fix this?

![skarmavbild 2017-06-10 kl 00 24 10](https://user-images.githubusercontent.com/4193514/26996553-3fd373f2-4d73-11e7-9eae-5260ccfef609.png)
"Not supported"

![skarmavbild 2017-06-10 kl 00 24 23](https://user-images.githubusercontent.com/4193514/26996555-4249690c-4d73-11e7-997c-bbade9477471.png)
"Unable to edit accessory
This accessory is blocked"

**Comment by astrojetson8** [comment]
i had similar issue with a bulb. i tried to everything, and only thing worked for me was i had remove the accessory from mi app, and add it again.

**Comment by iCarl** [comment]
I tried it already, but even if i remove it, it's still there

**Comment by astrojetson8** [comment]
i did too!

here's what i did:
1. remove the accessory in question from mi app
2. remove homebridge from Home (even at this stage i still had the old accessory and i still couldnt remove it)
3. clear accessory and persist folders
4. readd accessory in mi app
5. readd homebridge

**Comment by iCarl** [comment]
- I removed the accessory from the Mi App.
- I uninstalled Homebridge-Aqara and removed it from the config.json.
- I removed the persist folder and cashedAccessories.
- I removed Homebridge from Home App and added it again.

This still doesn't seem to remove the accessory from the Home App, and in some way, the "persist" folder reappears when i start Homebridge, with cashed information with my old accessories.

**Comment by astrojetson8** [comment]
did you also delete accessory folder?
one thing i forgot to mention was that i used kill command to stop homebridge before deleting accessory and persist folders

**Comment by silvetti** [comment]
Start with fresh Home configuration, so shutdown homebrige and delete persist and accesories folders in root where you have config.json file, restart homebridge and set it up on the phone and check.

**Comment by iCarl** [comment]
Changed plugin to "homebridge-mi-aqara", and got it working.
